import ProfileImg from "../assets/profile-img.jpg"

export const communityWorryPost = [
  {
    id: 1,
    title: "서울 연희동 데이트 코스",
    reg_at: "2023/07/12",
    src: ProfileImg,
    nick: "이니",
    content: "서울 연희동에서 놀려고 하는데, 비오는 날에도 재밌게 놀 수 있는 코스 없을까요? Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip hend",
    like: "43",
    view: "70",
    comment: "5",
    comment_list: [
      {id: 1, nick: "이니", reg_at: "2023/07/04", src: ProfileImg, content: "맛집 갔다가 소품샵을 들러보는건 어떨까요?",},
      {id: 2, nick: "주니", reg_at: "2023/07/05", src: ProfileImg, content: "저도 놀고싶어요",},
      {id: 3, nick: "헌터", reg_at: "2023/07/06", src: ProfileImg, content: "알게되면 저도 알려주세요",},
      {id: 4, nick: "키놈", reg_at: "2023/07/07", src: ProfileImg, content: "나만의 코스에서 찾아보세요",},
    ],
  },
  {
    id: 2,
    title: "안양 데이트 코스",
    reg_at: "2023/07/15",
    src: ProfileImg,
    nick: "키놈",
    content: "범계역 안양에서 놀만한 곳 추천해주세요",
    like: "53",
    view: "90",
    comment: "4",
        comment_list: [
      {id: 1, nick: "이니", reg_at: "2023/07/04", src: ProfileImg, content: "맛집 갔다가 소품샵을 들러보는건 어떨까요?",},
      {id: 2, nick: "주니", reg_at: "2023/07/05", src: ProfileImg, content: "저도 놀고싶어요",},
      {id: 3, nick: "헌터", reg_at: "2023/07/06", src: ProfileImg, content: "알게되면 저도 알려주세요",},
      {id: 4, nick: "키놈", reg_at: "2023/07/07", src: ProfileImg, content: "나만의 코스에서 찾아보세요",},
    ],
  },
  {
    id: 3,
    title: "이색 데이트 장소 추천",
    reg_at: "2023/07/18",
    src: ProfileImg,
    nick: "룰루",
    content: "맨날 남친이랑 밥집이랑 카페만 가서 재미없는데 좀 색다른 데이트 장소 없을까요?",
    like: "74",
    view: "80",
    comment: "2",
    comment_list: [
      {id: 1, nick: "이니", reg_at: "2023/07/04", src: ProfileImg, content: "맛집 갔다가 소품샵을 들러보는건 어떨까요?",},
      {id: 2, nick: "주니", reg_at: "2023/07/05", src: ProfileImg, content: "저도 놀고싶어요",},
      {id: 3, nick: "헌터", reg_at: "2023/07/06", src: ProfileImg, content: "알게되면 저도 알려주세요",},
      {id: 4, nick: "키놈", reg_at: "2023/07/07", src: ProfileImg, content: "나만의 코스에서 찾아보세요",},
    ],
  },
];
